### ISSUE TITLE
Space in source path needs to be quoted

### ISSUE THREAD

**Issue by 333fred** [jaredpar/basic-compilerlog#44]
![image](https://github.com/jaredpar/basic-compilerlog/assets/2371880/39fbf19d-670d-4ca1-9c54-863c8cd2b1c3)

**Comment by 333fred** [comment]
[7.0.306.zip](https://github.com/jaredpar/basic-compilerlog/files/11899102/7.0.306.zip)
Rename dthe binlog to .zip for upload

**Comment by 333fred** [comment]
To be specific, such file names need to be quoted, as there is actually a space in the name.

**Comment by jaredpar** [comment]
This was fixed a while ago and I added tests to verify it. If it's still showing up after latest let me know and we'll figure out what is going on here.

**Comment by 333fred** [comment]
@jaredpar a quick test with the above binlog shows the issue is still there. The path needs to be quoted, or the resultant rsp is invalid.

**Comment by jaredpar** [comment]
The path is quoted. I verified manually in the RSP and added tests for it. 

Think we are talking past each here on some point.

**Comment by jaredpar** [comment]
Oh I see, I have two code paths for generating the rsp: the rsp and the export command. One is quoting and the other is not.

**Comment by jaredpar** [comment]
<img width="379" alt="image" src="https://github.com/jaredpar/basic-compilerlog/assets/146967/e09b2491-232b-4103-92bc-9a35064fc0bb">
